# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_widget2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_edit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 818)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_20.addWidget(self.tableWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tag = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tag.setFont(font)
        self.tag.setObjectName("tag")
        self.horizontalLayout_10.addWidget(self.tag)
        self.tag_value = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tag_value.setFont(font)
        self.tag_value.setText("")
        self.tag_value.setObjectName("tag_value")
        self.horizontalLayout_10.addWidget(self.tag_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.module_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.module_type.setFont(font)
        self.module_type.setObjectName("module_type")
        self.horizontalLayout.addWidget(self.module_type)
        self.type_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_name.setFont(font)
        self.type_name.setText("")
        self.type_name.setObjectName("type_name")
        self.horizontalLayout.addWidget(self.type_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.NG_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NG_type.setFont(font)
        self.NG_type.setObjectName("NG_type")
        self.horizontalLayout_11.addWidget(self.NG_type)
        self.NG_value = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.NG_value.setFont(font)
        self.NG_value.setObjectName("NG_value")
        self.NG_value.addItem("")
        self.NG_value.addItem("")
        self.NG_value.addItem("")
        self.horizontalLayout_11.addWidget(self.NG_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.detection_algorithm = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.detection_algorithm.setFont(font)
        self.detection_algorithm.setObjectName("detection_algorithm")
        self.horizontalLayout_13.addWidget(self.detection_algorithm)
        self.dete_alg_value = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dete_alg_value.setFont(font)
        self.dete_alg_value.setObjectName("dete_alg_value")
        self.dete_alg_value.addItem("")
        self.dete_alg_value.addItem("")
        self.dete_alg_value.addItem("")
        self.dete_alg_value.addItem("")
        self.dete_alg_value.addItem("")
        self.horizontalLayout_13.addWidget(self.dete_alg_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_19.addWidget(self.save_button)
        self.tag_value_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tag_value_2.setFont(font)
        self.tag_value_2.setText("")
        self.tag_value_2.setObjectName("tag_value_2")
        self.horizontalLayout_19.addWidget(self.tag_value_2)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pcb = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pcb.setFont(font)
        self.pcb.setObjectName("pcb")
        self.horizontalLayout_15.addWidget(self.pcb)
        self.pcb_color = QtWidgets.QComboBox(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pcb_color.setFont(font)
        self.pcb_color.setObjectName("pcb_color")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.pcb_color.addItem("")
        self.horizontalLayout_15.addWidget(self.pcb_color)
        self.verticalLayout_21.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.component = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.component.setFont(font)
        self.component.setObjectName("component")
        self.horizontalLayout_16.addWidget(self.component)
        self.comp_color = QtWidgets.QComboBox(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comp_color.setFont(font)
        self.comp_color.setObjectName("comp_color")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.comp_color.addItem("")
        self.horizontalLayout_16.addWidget(self.comp_color)
        self.verticalLayout_21.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.detect = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.detect.setFont(font)
        self.detect.setObjectName("detect")
        self.horizontalLayout_17.addWidget(self.detect)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_17.addWidget(self.pushButton_3)
        self.verticalLayout_21.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_54.addLayout(self.verticalLayout_21)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.n_x_threshold_4 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_4.setFont(font)
        self.n_x_threshold_4.setObjectName("n_x_threshold_4")
        self.verticalLayout_7.addWidget(self.n_x_threshold_4)
        self.template_image = QtWidgets.QLabel(self.page)
        self.template_image.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.template_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image.setText("")
        self.template_image.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image.setObjectName("template_image")
        self.verticalLayout_7.addWidget(self.template_image)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 9)
        self.horizontalLayout_54.addLayout(self.verticalLayout_7)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_54)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_21.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_21.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_22.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_22.addWidget(self.pushButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.NG_type_2 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.NG_type_2.setFont(font)
        self.NG_type_2.setObjectName("NG_type_2")
        self.horizontalLayout_6.addWidget(self.NG_type_2)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_33.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.g_PN_threshold = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.g_PN_threshold.setFont(font)
        self.g_PN_threshold.setObjectName("g_PN_threshold")
        self.horizontalLayout_4.addWidget(self.g_PN_threshold)
        self.g_PN_threshold_value = QtWidgets.QDoubleSpinBox(self.page_2)
        self.g_PN_threshold_value.setDecimals(0)
        self.g_PN_threshold_value.setMinimum(-100.0)
        self.g_PN_threshold_value.setMaximum(100.0)
        self.g_PN_threshold_value.setSingleStep(1.0)
        # self.g_PN_threshold_value.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.g_PN_threshold_value.setProperty("value", 20.0)
        self.g_PN_threshold_value.setObjectName("g_PN_threshold_value")
        self.horizontalLayout_4.addWidget(self.g_PN_threshold_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.g_difference = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.g_difference.setFont(font)
        self.g_difference.setObjectName("g_difference")
        self.horizontalLayout_2.addWidget(self.g_difference)
        self.g_difference_value = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.g_difference_value.setFont(font)
        self.g_difference_value.setText("")
        self.g_difference_value.setObjectName("g_difference_value")
        self.horizontalLayout_2.addWidget(self.g_difference_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.g_result = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.g_result.setFont(font)
        self.g_result.setObjectName("g_result")
        self.horizontalLayout_3.addWidget(self.g_result)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_33.addLayout(self.verticalLayout_2)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_33)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.n_x_threshold_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_6.setFont(font)
        self.n_x_threshold_6.setObjectName("n_x_threshold_6")
        self.horizontalLayout_24.addWidget(self.n_x_threshold_6)
        self.start_interval_4 = QtWidgets.QLineEdit(self.page_3)
        self.start_interval_4.setObjectName("start_interval_4")
        self.horizontalLayout_24.addWidget(self.start_interval_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_25.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_25.addWidget(self.pushButton_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_26.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.n_x_threshold_5 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_5.setFont(font)
        self.n_x_threshold_5.setObjectName("n_x_threshold_5")
        self.verticalLayout_9.addWidget(self.n_x_threshold_5)
        self.template_image_4 = QtWidgets.QLabel(self.page_3)
        self.template_image_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.template_image_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image_4.setText("")
        self.template_image_4.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image_4.setObjectName("template_image_4")
        self.verticalLayout_9.addWidget(self.template_image_4)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 9)
        self.horizontalLayout_26.addLayout(self.verticalLayout_9)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(self.page_5)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ribbon = QtWidgets.QLabel(self.tab)
        self.ribbon.setObjectName("ribbon")
        self.verticalLayout_5.addWidget(self.ribbon)
        self.ribbonHei = QtWidgets.QLabel(self.tab)
        self.ribbonHei.setObjectName("ribbonHei")
        self.verticalLayout_5.addWidget(self.ribbonHei)
        self.ribbonDis = QtWidgets.QLabel(self.tab)
        self.ribbonDis.setObjectName("ribbonDis")
        self.verticalLayout_5.addWidget(self.ribbonDis)
        self.parDis = QtWidgets.QLabel(self.tab)
        self.parDis.setObjectName("parDis")
        self.verticalLayout_5.addWidget(self.parDis)
        self.matchDis = QtWidgets.QLabel(self.tab)
        self.matchDis.setObjectName("matchDis")
        self.verticalLayout_5.addWidget(self.matchDis)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ribbonValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.ribbonValue.setDecimals(1)
        self.ribbonValue.setMinimum(0.0)
        self.ribbonValue.setMaximum(10.0)
        self.ribbonValue.setSingleStep(1.0)
        # self.ribbonValue.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ribbonValue.setProperty("value", 5.0)
        self.ribbonValue.setObjectName("ribbonValue")
        self.verticalLayout_6.addWidget(self.ribbonValue)
        self.ribbonHValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.ribbonHValue.setDecimals(1)
        self.ribbonHValue.setMinimum(0.0)
        self.ribbonHValue.setMaximum(10.0)
        self.ribbonHValue.setSingleStep(1.0)
        # self.ribbonHValue.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ribbonHValue.setProperty("value", 4.0)
        self.ribbonHValue.setObjectName("ribbonHValue")
        self.verticalLayout_6.addWidget(self.ribbonHValue)
        self.ribbonDisValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.ribbonDisValue.setDecimals(1)
        self.ribbonDisValue.setMinimum(0.0)
        self.ribbonDisValue.setMaximum(20.0)
        self.ribbonDisValue.setSingleStep(1.0)
        # self.ribbonDisValue.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.ribbonDisValue.setProperty("value", 10.0)
        self.ribbonDisValue.setObjectName("ribbonDisValue")
        self.verticalLayout_6.addWidget(self.ribbonDisValue)
        self.parDisValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.parDisValue.setDecimals(1)
        self.parDisValue.setMinimum(0.0)
        self.parDisValue.setMaximum(50.0)
        self.parDisValue.setSingleStep(1.0)
        # self.parDisValue.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.parDisValue.setProperty("value", 30.0)
        self.parDisValue.setObjectName("parDisValue")
        self.verticalLayout_6.addWidget(self.parDisValue)
        self.matchDisValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.matchDisValue.setDecimals(1)
        self.matchDisValue.setMinimum(0.0)
        self.matchDisValue.setMaximum(100.0)
        self.matchDisValue.setSingleStep(1.0)
        # self.matchDisValue.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.matchDisValue.setProperty("value", 70.0)
        self.matchDisValue.setObjectName("matchDisValue")
        self.verticalLayout_6.addWidget(self.matchDisValue)
        self.scoreValue = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.scoreValue.setFont(font)
        self.scoreValue.setText("")
        self.scoreValue.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreValue.setObjectName("scoreValue")
        self.verticalLayout_6.addWidget(self.scoreValue)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.template_image_2 = QtWidgets.QLabel(self.tab)
        self.template_image_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.template_image_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image_2.setText("")
        self.template_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image_2.setObjectName("template_image_2")
        self.horizontalLayout_8.addWidget(self.template_image_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_18.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.n_x_threshold_2 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_2.setFont(font)
        self.n_x_threshold_2.setObjectName("n_x_threshold_2")
        self.horizontalLayout_51.addWidget(self.n_x_threshold_2)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.similarValue = QtWidgets.QDoubleSpinBox(self.page_4)
        self.similarValue.setDecimals(1)
        self.similarValue.setMinimum(0.0)
        self.similarValue.setMaximum(100.0)
        self.similarValue.setSingleStep(1.0)
        # self.similarValue.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.similarValue.setProperty("value", 50.0)
        self.similarValue.setObjectName("similarValue")
        self.horizontalLayout_52.addWidget(self.similarValue)
        self.min_unit_2 = QtWidgets.QLabel(self.page_4)
        self.min_unit_2.setObjectName("min_unit_2")
        self.horizontalLayout_52.addWidget(self.min_unit_2)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_52)
        self.verticalLayout_20.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_12.addWidget(self.pushButton_19)
        self.verticalLayout_20.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_53.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.n_x_threshold_10 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_10.setFont(font)
        self.n_x_threshold_10.setObjectName("n_x_threshold_10")
        self.verticalLayout_19.addWidget(self.n_x_threshold_10)
        self.template_image_5 = QtWidgets.QLabel(self.page_4)
        self.template_image_5.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.template_image_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image_5.setText("")
        self.template_image_5.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image_5.setObjectName("template_image_5")
        self.verticalLayout_19.addWidget(self.template_image_5)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 9)
        self.horizontalLayout_53.addLayout(self.verticalLayout_19)
        self.horizontalLayout_56.addLayout(self.horizontalLayout_53)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_22.addWidget(self.stackedWidget)
        self.horizontalLayout_57.addLayout(self.verticalLayout_22)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 364))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.template_image_3 = QtWidgets.QLabel(Form)
        self.template_image_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.template_image_3.setToolTip("")
        self.template_image_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image_3.setText("")
        self.template_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image_3.setObjectName("template_image_3")
        self.verticalLayout_4.addWidget(self.template_image_3)
        self.verticalLayout_4.setStretch(0, 8)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 8)
        self.horizontalLayout_57.addLayout(self.verticalLayout_4)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_57)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NG类型"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "子件名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "检测结果"))
        self.tag.setText(_translate("Form", "位号："))
        self.module_type.setText(_translate("Form", "子件类型："))
        self.NG_type.setText(_translate("Form", "NG类型："))
        self.NG_value.setItemText(0, _translate("Form", "漏件"))
        self.NG_value.setItemText(1, _translate("Form", "极反"))
        self.NG_value.setItemText(2, _translate("Form", "错件"))
        self.detection_algorithm.setText(_translate("Form", "检测算法："))
        self.dete_alg_value.setItemText(0, _translate("Form", "模板匹配"))
        self.dete_alg_value.setItemText(1, _translate("Form", "灰度差"))
        self.dete_alg_value.setItemText(2, _translate("Form", "OCR识别"))
        self.dete_alg_value.setItemText(3, _translate("Form", "颜色匹配"))
        self.dete_alg_value.setItemText(4, _translate("Form", "颜色提取"))
        self.save_button.setText(_translate("Form", "保存"))
        self.pcb.setText(_translate("Form", "PCB板颜色:"))
        self.pcb_color.setItemText(0, _translate("Form", "绿色"))
        self.pcb_color.setItemText(1, _translate("Form", "蓝色"))
        self.pcb_color.setItemText(2, _translate("Form", "红色"))
        self.pcb_color.setItemText(3, _translate("Form", "黄色"))
        self.pcb_color.setItemText(4, _translate("Form", "紫色"))
        self.pcb_color.setItemText(5, _translate("Form", "白色"))
        self.pcb_color.setItemText(6, _translate("Form", "黑色"))
        self.component.setText(_translate("Form", "元件颜色:"))
        self.comp_color.setItemText(0, _translate("Form", "绿色"))
        self.comp_color.setItemText(1, _translate("Form", "蓝色"))
        self.comp_color.setItemText(2, _translate("Form", "红色"))
        self.comp_color.setItemText(3, _translate("Form", "黄色"))
        self.comp_color.setItemText(4, _translate("Form", "紫色"))
        self.comp_color.setItemText(5, _translate("Form", "白色"))
        self.comp_color.setItemText(6, _translate("Form", "黑色"))
        self.detect.setText(_translate("Form", "检测"))
        self.pushButton_3.setText(_translate("Form", "生成模板"))
        self.n_x_threshold_4.setText(_translate("Form", "模板图像"))
        self.pushButton_9.setText(_translate("Form", "正负上下旋转"))
        self.pushButton_10.setText(_translate("Form", "正负左右旋转"))
        self.pushButton_11.setText(_translate("Form", "正负上下反转"))
        self.pushButton_12.setText(_translate("Form", "正负左右反转"))
        self.pushButton_2.setText(_translate("Form", "获取检测区间"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:8pt;\"><br/></span></p></body></html>"))
        self.NG_type_2.setText(_translate("Form", "极性检测算法："))
        self.pushButton.setText(_translate("Form", "检测"))
        self.g_PN_threshold.setText(_translate("Form", "正负极灰度差阈值:"))
        self.g_difference.setText(_translate("Form", "正负极灰度差:"))
        self.g_result.setText(_translate("Form", "极性检测结果:"))
        self.n_x_threshold_6.setText(_translate("Form", "模板内容："))
        self.pushButton_5.setText(_translate("Form", "旋转"))
        self.pushButton_4.setText(_translate("Form", "生成模板"))
        self.n_x_threshold_5.setText(_translate("Form", "模板图像"))
        self.ribbon.setText(_translate("Form", "色带数："))
        self.ribbonHei.setText(_translate("Form", "色带宽度："))
        self.ribbonDis.setText(_translate("Form", "色带距离："))
        self.parDis.setText(_translate("Form", "分割阈值："))
        self.matchDis.setText(_translate("Form", "匹配阈值："))
        self.label_12.setText(_translate("Form", "评分："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "分割法"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "抽色法"))
        self.n_x_threshold_2.setText(_translate("Form", "相似度阈值:"))
        self.min_unit_2.setText(_translate("Form", "%"))
        self.pushButton_19.setText(_translate("Form", "生成模板"))
        self.n_x_threshold_10.setText(_translate("Form", "模板图像"))

