# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_widget1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_edit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 818)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_19.addWidget(self.tableWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.module_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.module_type.setFont(font)
        self.module_type.setObjectName("module_type")
        self.horizontalLayout.addWidget(self.module_type)
        self.type_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_name.setFont(font)
        self.type_name.setObjectName("type_name")
        self.horizontalLayout.addWidget(self.type_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.module_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.module_name.setFont(font)
        self.module_name.setObjectName("module_name")
        self.horizontalLayout_10.addWidget(self.module_name)
        self.name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.horizontalLayout_10.addWidget(self.name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.NG_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NG_type.setFont(font)
        self.NG_type.setObjectName("NG_type")
        self.horizontalLayout_11.addWidget(self.NG_type)
        self.NG_value = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.NG_value.setFont(font)
        self.NG_value.setObjectName("NG_value")
        self.NG_value.addItem("")
        self.NG_value.addItem("")
        self.NG_value.addItem("")
        self.horizontalLayout_11.addWidget(self.NG_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.segmentation_algorithm = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.segmentation_algorithm.setFont(font)
        self.segmentation_algorithm.setObjectName("segmentation_algorithm")
        self.horizontalLayout_12.addWidget(self.segmentation_algorithm)
        self.seg_alg_value = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.seg_alg_value.setFont(font)
        self.seg_alg_value.setObjectName("seg_alg_value")
        self.seg_alg_value.addItem("")
        self.seg_alg_value.addItem("")
        self.horizontalLayout_12.addWidget(self.seg_alg_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.detection_algorithm = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.detection_algorithm.setFont(font)
        self.detection_algorithm.setObjectName("detection_algorithm")
        self.horizontalLayout_13.addWidget(self.detection_algorithm)
        self.dete_alg_value = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dete_alg_value.setFont(font)
        self.dete_alg_value.setObjectName("dete_alg_value")
        self.dete_alg_value.addItem("")
        self.dete_alg_value.addItem("")
        self.horizontalLayout_13.addWidget(self.dete_alg_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19.addLayout(self.verticalLayout_3)
        self.horizontalLayout_19.setStretch(0, 2)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(Form)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.colour_area = QtWidgets.QLabel(self.page_3)
        self.colour_area.setObjectName("colour_area")
        self.horizontalLayout_16.addWidget(self.colour_area)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.NG_value_2 = QtWidgets.QComboBox(self.page_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NG_value_2.setFont(font)
        self.NG_value_2.setObjectName("NG_value_2")
        self.NG_value_2.addItem("")
        self.NG_value_2.addItem("")
        self.horizontalLayout_14.addWidget(self.NG_value_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.start_interval = QtWidgets.QLineEdit(self.page_3)
        self.start_interval.setObjectName("start_interval")
        self.gridLayout.addWidget(self.start_interval, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_9.addWidget(self.stackedWidget_2)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.gray_ifference = QtWidgets.QWidget()
        self.gray_ifference.setObjectName("gray_ifference")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.gray_ifference)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.NG_type_2 = QtWidgets.QLabel(self.gray_ifference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.NG_type_2.setFont(font)
        self.NG_type_2.setObjectName("NG_type_2")
        self.gridLayout_3.addWidget(self.NG_type_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gray_ifference)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.NG_type_3 = QtWidgets.QLabel(self.gray_ifference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.NG_type_3.setFont(font)
        self.NG_type_3.setObjectName("NG_type_3")
        self.gridLayout_4.addWidget(self.NG_type_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.start_interval_2 = QtWidgets.QLineEdit(self.gray_ifference)
        self.start_interval_2.setObjectName("start_interval_2")
        self.gridLayout_5.addWidget(self.start_interval_2, 1, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.g_PN_threshold = QtWidgets.QLabel(self.gray_ifference)
        self.g_PN_threshold.setObjectName("g_PN_threshold")
        self.horizontalLayout_4.addWidget(self.g_PN_threshold)
        self.g_PN_threshold_value = QtWidgets.QDoubleSpinBox(self.gray_ifference)
        self.g_PN_threshold_value.setDecimals(1)
        self.g_PN_threshold_value.setMinimum(0.0)
        self.g_PN_threshold_value.setMaximum(100.0)
        self.g_PN_threshold_value.setSingleStep(1.0)
        # self.g_PN_threshold_value.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.g_PN_threshold_value.setProperty("value", 100.0)
        self.g_PN_threshold_value.setObjectName("g_PN_threshold_value")
        self.horizontalLayout_4.addWidget(self.g_PN_threshold_value)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.g_difference = QtWidgets.QLabel(self.gray_ifference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.g_difference.setFont(font)
        self.g_difference.setObjectName("g_difference")
        self.horizontalLayout_2.addWidget(self.g_difference)
        self.g_difference_value = QtWidgets.QLabel(self.gray_ifference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.g_difference_value.setFont(font)
        self.g_difference_value.setText("")
        self.g_difference_value.setAlignment(QtCore.Qt.AlignCenter)
        self.g_difference_value.setObjectName("g_difference_value")
        self.horizontalLayout_2.addWidget(self.g_difference_value)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.g_result = QtWidgets.QLabel(self.gray_ifference)
        self.g_result.setObjectName("g_result")
        self.horizontalLayout_3.addWidget(self.g_result)
        self.label_4 = QtWidgets.QLabel(self.gray_ifference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_18.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.gray_ifference, "")
        self.quantity_difference = QtWidgets.QWidget()
        self.quantity_difference.setObjectName("quantity_difference")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.quantity_difference)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.n_x_threshold = QtWidgets.QLabel(self.quantity_difference)
        self.n_x_threshold.setObjectName("n_x_threshold")
        self.horizontalLayout_5.addWidget(self.n_x_threshold)
        self.n_x_threshold_value = QtWidgets.QDoubleSpinBox(self.quantity_difference)
        self.n_x_threshold_value.setDecimals(1)
        self.n_x_threshold_value.setMinimum(0.0)
        self.n_x_threshold_value.setMaximum(100.0)
        self.n_x_threshold_value.setSingleStep(1.0)
        self.n_x_threshold_value.setProperty("value", 100.0)
        self.n_x_threshold_value.setObjectName("n_x_threshold_value")
        self.horizontalLayout_5.addWidget(self.n_x_threshold_value)
        self.n_x_unit = QtWidgets.QLabel(self.quantity_difference)
        self.n_x_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.n_x_unit.setObjectName("n_x_unit")
        self.horizontalLayout_5.addWidget(self.n_x_unit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.n_y_threshold = QtWidgets.QLabel(self.quantity_difference)
        self.n_y_threshold.setObjectName("n_y_threshold")
        self.horizontalLayout_8.addWidget(self.n_y_threshold)
        self.n_y_threshold_value = QtWidgets.QDoubleSpinBox(self.quantity_difference)
        self.n_y_threshold_value.setDecimals(1)
        self.n_y_threshold_value.setMinimum(0.0)
        self.n_y_threshold_value.setSingleStep(1.0)
        self.n_y_threshold_value.setProperty("value", 100.0)
        self.n_y_threshold_value.setObjectName("n_y_threshold_value")
        self.horizontalLayout_8.addWidget(self.n_y_threshold_value)
        self.n_y_unit = QtWidgets.QLabel(self.quantity_difference)
        self.n_y_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.n_y_unit.setObjectName("n_y_unit")
        self.horizontalLayout_8.addWidget(self.n_y_unit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.n_PN_threshold = QtWidgets.QLabel(self.quantity_difference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.n_PN_threshold.setFont(font)
        self.n_PN_threshold.setObjectName("n_PN_threshold")
        self.horizontalLayout_6.addWidget(self.n_PN_threshold)
        self.n_PN_threshold_value = QtWidgets.QDoubleSpinBox(self.quantity_difference)
        self.n_PN_threshold_value.setDecimals(1)
        self.n_PN_threshold_value.setMinimum(0.0)
        self.n_PN_threshold_value.setMaximum(100.0)
        self.n_PN_threshold_value.setSingleStep(1.0)
        # self.n_PN_threshold_value.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.n_PN_threshold_value.setProperty("value", 100.0)
        self.n_PN_threshold_value.setObjectName("n_PN_threshold_value")
        self.horizontalLayout_6.addWidget(self.n_PN_threshold_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.n_difference = QtWidgets.QLabel(self.quantity_difference)
        self.n_difference.setObjectName("n_difference")
        self.horizontalLayout_9.addWidget(self.n_difference)
        self.n_difference_value = QtWidgets.QLabel(self.quantity_difference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.n_difference_value.setFont(font)
        self.n_difference_value.setAlignment(QtCore.Qt.AlignCenter)
        self.n_difference_value.setObjectName("n_difference_value")
        self.horizontalLayout_9.addWidget(self.n_difference_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.detect_result = QtWidgets.QLabel(self.quantity_difference)
        self.detect_result.setObjectName("detect_result")
        self.horizontalLayout_7.addWidget(self.detect_result)
        self.detect_result_value = QtWidgets.QLabel(self.quantity_difference)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.detect_result_value.setFont(font)
        self.detect_result_value.setAlignment(QtCore.Qt.AlignCenter)
        self.detect_result_value.setObjectName("detect_result_value")
        self.horizontalLayout_7.addWidget(self.detect_result_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_23.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.quantity_difference, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.choose_template = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.choose_template.setFont(font)
        self.choose_template.setObjectName("choose_template")
        self.verticalLayout_8.addWidget(self.choose_template)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.n_x_threshold_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.n_x_threshold_2.setFont(font)
        self.n_x_threshold_2.setObjectName("n_x_threshold_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.n_x_threshold_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.similarValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.similarValue.setDecimals(1)
        self.similarValue.setMinimum(0.0)
        self.similarValue.setMaximum(100.0)
        self.similarValue.setSingleStep(1.0)
        # self.similarValue.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.similarValue.setProperty("value", 0.0)
        self.similarValue.setObjectName("similarValue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.similarValue)
        self.min_unit_2 = QtWidgets.QLabel(self.tab)
        self.min_unit_2.setObjectName("min_unit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.min_unit_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.horizontalLayout_25.addLayout(self.verticalLayout_8)
        self.template_image = QtWidgets.QLabel(self.tab)
        self.template_image.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.template_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.template_image.setText("")
        self.template_image.setAlignment(QtCore.Qt.AlignCenter)
        self.template_image.setObjectName("template_image")
        self.horizontalLayout_25.addWidget(self.template_image)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_24.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget = QtWidgets.QWidget(self.page_2)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 20, 95, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.generate_parameters = QtWidgets.QPushButton(self.layoutWidget)
        self.generate_parameters.setObjectName("generate_parameters")
        self.verticalLayout_5.addWidget(self.generate_parameters)
        self.detect = QtWidgets.QPushButton(self.layoutWidget)
        self.detect.setObjectName("detect")
        self.verticalLayout_5.addWidget(self.detect)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 13, 301, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.min_area = QtWidgets.QLabel(self.layoutWidget1)
        self.min_area.setObjectName("min_area")
        self.horizontalLayout_21.addWidget(self.min_area)
        self.min_area_value = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.min_area_value.setDecimals(1)
        self.min_area_value.setMinimum(0.0)
        self.min_area_value.setSingleStep(1.0)
        self.min_area_value.setObjectName("min_area_value")
        self.horizontalLayout_21.addWidget(self.min_area_value)
        self.min_unit = QtWidgets.QLabel(self.layoutWidget1)
        self.min_unit.setObjectName("min_unit")
        self.horizontalLayout_21.addWidget(self.min_unit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.max_area = QtWidgets.QLabel(self.layoutWidget1)
        self.max_area.setObjectName("max_area")
        self.horizontalLayout_20.addWidget(self.max_area)
        self.max_area_value = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.max_area_value.setDecimals(1)
        self.max_area_value.setMinimum(0.0)
        self.max_area_value.setMaximum(100.0)
        self.max_area_value.setSingleStep(1.0)
        self.max_area_value.setObjectName("max_area_value")
        self.horizontalLayout_20.addWidget(self.max_area_value)
        self.max_unit = QtWidgets.QLabel(self.layoutWidget1)
        self.max_unit.setObjectName("max_unit")
        self.horizontalLayout_20.addWidget(self.max_unit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.measurements = QtWidgets.QLabel(self.layoutWidget1)
        self.measurements.setObjectName("measurements")
        self.horizontalLayout_22.addWidget(self.measurements)
        self.mea_value = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mea_value.setObjectName("mea_value")
        self.horizontalLayout_22.addWidget(self.mea_value)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.horizontalLayout_27.addLayout(self.verticalLayout_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 391))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 550, 390))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.horizontalLayout_27.addLayout(self.verticalLayout_7)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)

        self.retranslateUi(Form)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NG类型"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "子件名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "检测结果"))
        self.module_type.setText(_translate("Form", "类型："))
        self.type_name.setText(_translate("Form", "电容"))
        self.module_name.setText(_translate("Form", "名称："))
        self.name.setText(_translate("Form", "电阻"))
        self.NG_type.setText(_translate("Form", "NG类型："))
        self.NG_value.setItemText(0, _translate("Form", "极反"))
        self.NG_value.setItemText(1, _translate("Form", "错件"))
        self.NG_value.setItemText(2, _translate("Form", "漏件"))
        self.segmentation_algorithm.setText(_translate("Form", "分割算法："))
        self.seg_alg_value.setItemText(0, _translate("Form", "算法1"))
        self.seg_alg_value.setItemText(1, _translate("Form", "算法2"))
        self.detection_algorithm.setText(_translate("Form", "检测算法："))
        self.dete_alg_value.setItemText(0, _translate("Form", "模板匹配"))
        self.dete_alg_value.setItemText(1, _translate("Form", "灰度值"))
        self.colour_area.setText(_translate("Form", "颜色值域"))
        self.label_3.setText(_translate("Form", "分割方法"))
        self.label_5.setText(_translate("Form", "分割方法:"))
        self.NG_value_2.setItemText(0, _translate("Form", "自动调整"))
        self.NG_value_2.setItemText(1, _translate("Form", "手动调整"))
        self.label_6.setText(_translate("Form", "自适应区间:"))
        self.NG_type_2.setText(_translate("Form", "极性检测算法："))
        self.pushButton.setText(_translate("Form", "检测"))
        self.NG_type_3.setText(_translate("Form", "检测区域："))
        self.g_PN_threshold.setText(_translate("Form", "正负极灰度差阈值:"))
        self.g_difference.setText(_translate("Form", "正负极灰度差:"))
        self.g_result.setText(_translate("Form", "极性检测结果:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gray_ifference), _translate("Form", "灰度差"))
        self.n_x_threshold.setText(_translate("Form", "X方向偏移阈值:"))
        self.n_x_unit.setText(_translate("Form", "pixel"))
        self.n_y_threshold.setText(_translate("Form", "Y方向偏移阈值:"))
        self.n_y_unit.setText(_translate("Form", "pixel"))
        self.n_PN_threshold.setText(_translate("Form", "正负极数量差阈值:"))
        self.n_difference.setText(_translate("Form", "数量差:"))
        self.n_difference_value.setText(_translate("Form", "100"))
        self.detect_result.setText(_translate("Form", "极性检测结果:"))
        self.detect_result_value.setText(_translate("Form", "正极"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.quantity_difference), _translate("Form", "数量差"))
        self.choose_template.setText(_translate("Form", "选择模板"))
        self.n_x_threshold_2.setText(_translate("Form", "相似度:"))
        self.min_unit_2.setText(_translate("Form", "%"))
        self.pushButton_3.setText(_translate("Form", "生成模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "漏件模板"))
        self.generate_parameters.setText(_translate("Form", "生成参数"))
        self.detect.setText(_translate("Form", "检测"))
        self.min_area.setText(_translate("Form", "面积比例下限至:"))
        self.min_unit.setText(_translate("Form", "%"))
        self.max_area.setText(_translate("Form", "面积比例上限至:"))
        self.max_unit.setText(_translate("Form", "%"))
        self.measurements.setText(_translate("Form", "测量值:"))

