# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'online_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 937)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/xiashu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.horizontalLayout.addWidget(self.videoLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.toolBar.setFont(font)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.patternSelectAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/folder-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patternSelectAction.setIcon(icon1)
        self.patternSelectAction.setObjectName("patternSelectAction")
        self.startAction = QtWidgets.QAction(MainWindow)
        self.startAction.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar/play-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAction.setIcon(icon2)
        self.startAction.setObjectName("startAction")
        self.stopAction = QtWidgets.QAction(MainWindow)
        self.stopAction.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/stop-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopAction.setIcon(icon3)
        self.stopAction.setObjectName("stopAction")
        self.cameraOpenAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/camera-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraOpenAction.setIcon(icon4)
        self.cameraOpenAction.setObjectName("cameraOpenAction")
        self.cameraCloseAction = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbar/camera-50-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraCloseAction.setIcon(icon5)
        self.cameraCloseAction.setObjectName("cameraCloseAction")
        self.parameterAction = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolbar/gear-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parameterAction.setIcon(icon6)
        self.parameterAction.setObjectName("parameterAction")
        self.videoAction = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolbar/video-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.videoAction.setIcon(icon7)
        self.videoAction.setObjectName("videoAction")
        self.designAction = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolbar/design-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.designAction.setIcon(icon8)
        self.designAction.setObjectName("designAction")
        self.toolBar.addAction(self.patternSelectAction)
        self.toolBar.addAction(self.startAction)
        self.toolBar.addAction(self.stopAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.cameraOpenAction)
        self.toolBar.addAction(self.cameraCloseAction)
        self.toolBar.addAction(self.videoAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.parameterAction)
        self.toolBar.addAction(self.designAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "全自动光学检测系统-夏数科技"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PCB版号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "子件名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "检测结果"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.patternSelectAction.setText(_translate("MainWindow", "选择程式"))
        self.patternSelectAction.setToolTip(_translate("MainWindow", "选择程式"))
        self.patternSelectAction.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.startAction.setText(_translate("MainWindow", "开始检测"))
        self.startAction.setToolTip(_translate("MainWindow", "开始检测"))
        self.startAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.stopAction.setText(_translate("MainWindow", "停止检测"))
        self.stopAction.setToolTip(_translate("MainWindow", "停止检测"))
        self.stopAction.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.cameraOpenAction.setText(_translate("MainWindow", "打开相机"))
        self.cameraOpenAction.setToolTip(_translate("MainWindow", "打开相机"))
        self.cameraCloseAction.setText(_translate("MainWindow", "关闭相机"))
        self.cameraCloseAction.setToolTip(_translate("MainWindow", "关闭相机"))
        self.parameterAction.setText(_translate("MainWindow", "参数设置"))
        self.parameterAction.setToolTip(_translate("MainWindow", "参数设置"))
        self.videoAction.setText(_translate("MainWindow", "载入视频"))
        self.videoAction.setToolTip(_translate("MainWindow", "载入视频"))
        self.designAction.setText(_translate("MainWindow", "程式设计"))
        self.designAction.setToolTip(_translate("MainWindow", "程式设计"))

from ui import icon_rc
