# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pattern_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 838)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/xiashu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 768, 732))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rightTopArea = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rightTopArea.setFont(font)
        self.rightTopArea.setStyleSheet("")
        self.rightTopArea.setObjectName("rightTopArea")
        self.verticalLayout_2.addWidget(self.rightTopArea)
        self.rightUnderArea = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.rightUnderArea.setFont(font)
        self.rightUnderArea.setObjectName("rightUnderArea")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rightUnderArea.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.tab_7)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setEnabled(False)
        self.label_2.setAccessibleName("")
        self.label_2.setAccessibleDescription("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.listView)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.rightUnderArea.addTab(self.tab_7, "")
        self.verticalLayout_2.addWidget(self.rightUnderArea)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.toolBar.setFont(font)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.createAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/create-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createAction.setIcon(icon1)
        self.createAction.setObjectName("createAction")
        self.captureAction = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar/cap-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.captureAction.setIcon(icon2)
        self.captureAction.setObjectName("captureAction")
        self.zoomInAction = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/zoom-in-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInAction.setIcon(icon3)
        self.zoomInAction.setObjectName("zoomInAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/save-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAction.setIcon(icon4)
        self.saveAction.setObjectName("saveAction")
        self.openAction = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbar/folder-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon5)
        self.openAction.setObjectName("openAction")
        self.cursorAction = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolbar/cursor-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cursorAction.setIcon(icon6)
        self.cursorAction.setObjectName("cursorAction")
        self.zoomOutAction = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolbar/zoom-out-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutAction.setIcon(icon7)
        self.zoomOutAction.setObjectName("zoomOutAction")
        self.pcbLocationAction = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolbar/1_pcb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pcbLocationAction.setIcon(icon8)
        self.pcbLocationAction.setObjectName("pcbLocationAction")
        self.templateAction = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/toolbar/green-flag-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.templateAction.setIcon(icon9)
        self.templateAction.setObjectName("templateAction")
        self.maskAction = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toolbar/mask-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maskAction.setIcon(icon10)
        self.maskAction.setObjectName("maskAction")
        self.resistorAction = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/toolbar/resistor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resistorAction.setIcon(icon11)
        self.resistorAction.setObjectName("resistorAction")
        self.capacitorAction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/toolbar/capacitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capacitorAction.setIcon(icon12)
        self.capacitorAction.setObjectName("capacitorAction")
        self.slotAction = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/toolbar/slot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slotAction.setIcon(icon13)
        self.slotAction.setObjectName("slotAction")
        self.diodeAction = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/toolbar/diode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diodeAction.setIcon(icon14)
        self.diodeAction.setObjectName("diodeAction")
        self.componentAction = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/toolbar/component.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.componentAction.setIcon(icon15)
        self.componentAction.setObjectName("componentAction")
        self.homeAction = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/toolbar/home-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeAction.setIcon(icon16)
        self.homeAction.setObjectName("homeAction")
        self.toolBar.addAction(self.createAction)
        self.toolBar.addAction(self.saveAction)
        self.toolBar.addAction(self.openAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.captureAction)
        self.toolBar.addAction(self.zoomInAction)
        self.toolBar.addAction(self.zoomOutAction)
        self.toolBar.addAction(self.cursorAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.pcbLocationAction)
        self.toolBar.addAction(self.templateAction)
        self.toolBar.addAction(self.capacitorAction)
        self.toolBar.addAction(self.maskAction)
        self.toolBar.addAction(self.resistorAction)
        self.toolBar.addAction(self.slotAction)
        self.toolBar.addAction(self.diodeAction)
        self.toolBar.addAction(self.componentAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.homeAction)

        self.retranslateUi(MainWindow)
        self.rightTopArea.setCurrentIndex(-1)
        self.rightUnderArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "全自动光学检测系统-夏数科技"))
        self.rightUnderArea.setTabText(self.rightUnderArea.indexOf(self.tab_6), _translate("MainWindow", "相机播放"))
        self.pushButton.setText(_translate("MainWindow", "搜索"))
        self.pushButton_2.setText(_translate("MainWindow", "搜索"))
        self.label_3.setText(_translate("MainWindow", "类型："))
        self.label_2.setText(_translate("MainWindow", "料号："))
        self.groupBox.setTitle(_translate("MainWindow", "元件信息"))
        self.rightUnderArea.setTabText(self.rightUnderArea.indexOf(self.tab_7), _translate("MainWindow", "程式制作"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.createAction.setText(_translate("MainWindow", "新建程式"))
        self.createAction.setToolTip(_translate("MainWindow", "创建程式"))
        self.createAction.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.captureAction.setText(_translate("MainWindow", "抓取图片"))
        self.captureAction.setToolTip(_translate("MainWindow", "抓取图片"))
        self.captureAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.zoomInAction.setText(_translate("MainWindow", "放大"))
        self.zoomInAction.setToolTip(_translate("MainWindow", "放大"))
        self.zoomInAction.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.saveAction.setText(_translate("MainWindow", "保存程式"))
        self.saveAction.setToolTip(_translate("MainWindow", "保存程式"))
        self.openAction.setText(_translate("MainWindow", "打开程式"))
        self.openAction.setToolTip(_translate("MainWindow", "打开程式"))
        self.cursorAction.setText(_translate("MainWindow", "选择"))
        self.cursorAction.setToolTip(_translate("MainWindow", "选择"))
        self.zoomOutAction.setText(_translate("MainWindow", "缩小"))
        self.zoomOutAction.setToolTip(_translate("MainWindow", "缩小"))
        self.pcbLocationAction.setText(_translate("MainWindow", "PCB选择"))
        self.pcbLocationAction.setToolTip(_translate("MainWindow", "PCB选择"))
        self.templateAction.setText(_translate("MainWindow", "模板定位"))
        self.templateAction.setToolTip(_translate("MainWindow", "模板定位"))
        self.maskAction.setText(_translate("MainWindow", "Mask"))
        self.maskAction.setToolTip(_translate("MainWindow", "Mask"))
        self.resistorAction.setText(_translate("MainWindow", "色环电阻"))
        self.resistorAction.setToolTip(_translate("MainWindow", "色环电阻"))
        self.capacitorAction.setText(_translate("MainWindow", "电解电容"))
        self.capacitorAction.setToolTip(_translate("MainWindow", "电解电容"))
        self.slotAction.setText(_translate("MainWindow", "插槽"))
        self.slotAction.setToolTip(_translate("MainWindow", "插槽"))
        self.diodeAction.setText(_translate("MainWindow", "二极管"))
        self.diodeAction.setToolTip(_translate("MainWindow", "二极管"))
        self.componentAction.setText(_translate("MainWindow", "一般元件"))
        self.componentAction.setToolTip(_translate("MainWindow", "一般元件"))
        self.homeAction.setText(_translate("MainWindow", "检测界面"))
        self.homeAction.setToolTip(_translate("MainWindow", "检测界面"))

import icon_rc
