# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcb_location.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(662, 442)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupbox_1 = QtWidgets.QGroupBox(Form)
        self.groupbox_1.setObjectName("groupbox_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox_1)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupbox_1)
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupbox_1)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.getTemplateButton_2 = QtWidgets.QPushButton(self.groupbox_1)
        self.getTemplateButton_2.setObjectName("getTemplateButton_2")
        self.gridLayout.addWidget(self.getTemplateButton_2, 1, 2, 1, 1)
        self.getTemplateButton_1 = QtWidgets.QPushButton(self.groupbox_1)
        self.getTemplateButton_1.setObjectName("getTemplateButton_1")
        self.gridLayout.addWidget(self.getTemplateButton_1, 1, 0, 1, 1)
        self.templateLabel_1 = QtWidgets.QLabel(self.groupbox_1)
        self.templateLabel_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.templateLabel_1.setText("")
        self.templateLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.templateLabel_1.setObjectName("templateLabel_1")
        self.gridLayout.addWidget(self.templateLabel_1, 0, 0, 1, 1)
        self.templateLabel_2 = QtWidgets.QLabel(self.groupbox_1)
        self.templateLabel_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.templateLabel_2.setText("")
        self.templateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.templateLabel_2.setObjectName("templateLabel_2")
        self.gridLayout.addWidget(self.templateLabel_2, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(self.groupbox_1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupbox_1)
        self.groupbox_2 = QtWidgets.QGroupBox(Form)
        self.groupbox_2.setObjectName("groupbox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupbox_2)
        self.horizontalLayout_3.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pcbLabel = QtWidgets.QLabel(self.groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcbLabel.sizePolicy().hasHeightForWidth())
        self.pcbLabel.setSizePolicy(sizePolicy)
        self.pcbLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pcbLabel.setText("")
        self.pcbLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pcbLabel.setObjectName("pcbLabel")
        self.verticalLayout.addWidget(self.pcbLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.getPCBButton = QtWidgets.QPushButton(self.groupbox_2)
        self.getPCBButton.setObjectName("getPCBButton")
        self.horizontalLayout_2.addWidget(self.getPCBButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(self.groupbox_2)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupbox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_4.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupbox_1.setTitle(_translate("Form", "设置定位模板"))
        self.getTemplateButton_2.setText(_translate("Form", "获取模板2"))
        self.getTemplateButton_1.setText(_translate("Form", "获取模板1"))
        self.label.setText(_translate("Form", "提示：\n"
"选择合适标记点，移动选项框到相应位置，点击“提取模板”。"))
        self.groupbox_2.setTitle(_translate("Form", "PCB板区域提取"))
        self.getPCBButton.setText(_translate("Form", "获取PCB"))
        self.label_2.setText(_translate("Form", "提示：\n"
"选择合适标记点，移动选项框到相应位置，点击“提取模板”。"))
        self.saveButton.setText(_translate("Form", "保存并载入"))

